name: Deploy application to Heroku

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout the repository
      - uses: akhileshns/heroku-deploy@v3.13.15
        name: Deploy
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "roman-davydchuk-mkr"
          heroku_email: "roman.davydchuk@knu.ua"
